# Generated by Django 6.0.2 on 2026-03-03 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eHospitalapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Patient',
            new_name='MyPatient',
        ),
    ]
